# ex: set ro:
# DO NOT EDIT.
# generated by smc (http://smc.sourceforge.net/)
# from file : Avtomat.sm

import statemap


class AppClassState(statemap.State):

    def Entry(self, fsm):
        pass

    def Exit(self, fsm):
        pass

    def CheckChar(self, fsm, c, counter):
        self.Default(fsm)

    def CheckChar(self, fsm, counter, c):
        self.Default(fsm)

    def EOS(self, fsm, counter):
        self.Default(fsm)

    def nfs(self, fsm, counter, c):
        self.Default(fsm)

    def Default(self, fsm):
        msg = "\n\tState: %s\n\tTransition: %s" % (
            fsm.getState().getName(), fsm.getTransition())
        raise statemap.TransitionUndefinedException(msg)

class Map1_Default(AppClassState):

    def nfs(self, fsm, counter, c):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Invalid()
        finally:
            fsm.setState(Map1.Invalid)
            fsm.getState().Entry(fsm)

    def CheckChar(self, fsm, c, counter):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Invalid()
        finally:
            fsm.setState(Map1.Invalid)
            fsm.getState().Entry(fsm)

    def EOS(self, fsm, counter):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Invalid()
        finally:
            fsm.setState(Map1.Invalid)
            fsm.getState().Entry(fsm)

class Map1_Start(Map1_Default):

    def nfs(self, fsm, counter, c):
        ctxt = fsm.getOwner()
        if counter == 0 and c == "n" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.IncCounter()
            finally:
                fsm.setState(endState)
        elif counter == 1 and c == "f" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.IncCounter()
            finally:
                fsm.setState(endState)
        elif counter == 2 and c == "s" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.IncCounter()
            finally:
                fsm.setState(endState)
        elif counter == 3 and c == ":" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.IncCounter()
            finally:
                fsm.setState(endState)
        elif counter == 4 and c == "/" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.IncCounter()
            finally:
                fsm.setState(endState)
        elif counter == 5 and c == "/" :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.ResetCounter()
            finally:
                fsm.setState(Map1.Server)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.nfs(self, fsm, counter, c)
        
class Map1_Server(Map1_Default):

    def CheckChar(self, fsm, counter, c):
        ctxt = fsm.getOwner()
        if (c >= "a" and c <="z") or (c >= "A" and c<="Z")  :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.IncCounter()
            finally:
                fsm.setState(endState)
        elif counter > 0 and c == "/" :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.ResetCounter()
            finally:
                fsm.setState(Map1.Dir)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.CheckChar(self, fsm, counter, c)
        
class Map1_Dir(Map1_Default):

    def CheckChar(self, fsm, counter, c):
        ctxt = fsm.getOwner()
        if (c >= "a" and c <="z") or (c >= "A" and c<="Z")  :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.IncCounter()
            finally:
                fsm.setState(endState)
        elif counter > 0 and c == "/" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.ResetCounter()
            finally:
                fsm.setState(endState)
        else:
            Map1_Default.CheckChar(self, fsm, counter, c)
        
    def EOS(self, fsm, counter):
        ctxt = fsm.getOwner()
        if counter > 0 :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.Valid()
            finally:
                fsm.setState(Map1.Valid)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.EOS(self, fsm, counter)
        
class Map1_Valid(Map1_Default):
    pass

class Map1_Invalid(Map1_Default):
    pass

class Map1(object):

    Start = Map1_Start('Map1.Start', 0)
    Server = Map1_Server('Map1.Server', 1)
    Dir = Map1_Dir('Map1.Dir', 2)
    Valid = Map1_Valid('Map1.Valid', 3)
    Invalid = Map1_Invalid('Map1.Invalid', 4)
    Default = Map1_Default('Map1.Default', -1)

class AppClass_sm(statemap.FSMContext):

    def __init__(self, owner):
        statemap.FSMContext.__init__(self, Map1.Start)
        self._owner = owner

    def __getattr__(self, attrib):
        def trans_sm(*arglist):
            self._transition = attrib
            getattr(self.getState(), attrib)(self, *arglist)
            self._transition = None
        return trans_sm

    def enterStartState(self):
        self._state.Entry(self)

    def getOwner(self):
        return self._owner

# Local variables:
#  buffer-read-only: t
# End:
